---
name: Security

on: # yamllint disable-line rule:truthy
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

defaults:
  run:
    shell: sh

jobs:
  code-scanning:
    name: Code scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
        with:
          languages: "javascript"
      - name: Perform CodeQL Analysis
        id: codeql-analysis
        uses: github/codeql-action/analyze@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
      - name: Upload to GHAS
        if: always()
        uses: github/codeql-action/upload-sarif@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
        with:
          category: "code-scanning"
          sarif_file: "${{ steps.codeql-analysis.outputs.sarif-output }}"
  directory-scanning:
    name: Directory scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Scan current project
        id: scan-directory
        uses: anchore/scan-action@3343887d815d7b07465f6fdcd395bd66508d486a # v3
        with:
          by-cve: "true"
          path: "."
      - name: Upload to GHAS
        if: always()
        uses: github/codeql-action/upload-sarif@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
        with:
          category: "directory-scanning"
          sarif_file: "${{ steps.scan-directory.outputs.sarif }}"
